### ISSUE TITLE
vz.findStartCursorNextLineStartが異常に遅い

### ISSUE THREAD

**Issue by kato033** [tshino/vscode-vz-like-keymap#125]
2/18 の更新後、vz.findStartCursorNextLineStart の処理が異常に遅くなりました。
ctrl-J に割付けて使ってるのですが、長押しした時に、カーソル移動が追い付かず、キーを離してもすぐに止まらなくなりました。
バージョンを一つ前に戻すと問題無し。
何があったのでしょうか?

**Comment by tshino** [comment]
お知らせありがとうございます。
推測ですが #121 の修正と関係がありそうです。

VS Code 1.75.0 と VS Code 1.75.1 のあたりから一部のコマンドの動作に問題が起き始めました。
そのうちの1つ、CTRL+U（vz.undelete）の動作におきた問題は、特定の VS Code API の動作が変わったことが原因と分かったので対策を行いました（#121）。
他にも問題が起きていたのでいくつかは対策を行いました。

ここから推測ですが（これから確認しますが）、おそらく対策の影響で本件が起きていると予想しています。

**Comment by tshino** [comment]
まだ遅くなっているコマンドが残っている気がしますが、ひとまずvz.findStartCursorNextLineStartの動作は自分が確認した範囲では改善しました。

**Comment by tshino** [comment]
修正したものを v0.19.6 としてリリースしました。

**Comment by kato033** [comment]
修正を確認しました。
対応ありがとうございます。
