### ISSUE TITLE
差分表示の左ペインで、CTRL+Eが異なる動作をする。

### ISSUE THREAD

**Issue by kato033** [tshino/vscode-vz-like-keymap#267]
#237  でCtrl-Eの挙動について対応いただきましたが、_履歴の差分表示などの左ペインでの動作が変わらないようです。_ (右ペインにカーソルが飛ぶ)
(多分、他のキーも) 対応いただけると嬉しいです。

 -------------------------
申し訳ありません。理由は不明ながら、私の環境で、findstartCursorUp の whenが違っていました。 リセットしたところ、問題は解決しました。

**Comment by tshino** [comment]
すみません、おっしゃるような操作を調べてみたのですが、問題のある動作が見つかりませんでした。
具体的にどんな操作をしたときに、どうなるのか教えていただけますか？

**Comment by tshino** [comment]
解決したようで良かったです。
また何かあればお知らせ下さい。
