### ISSUE TITLE
キャッチできないエラー

### ISSUE THREAD

**Issue by kato033** [tshino/vscode-vz-like-keymap#41]
発生状況は絞れていませんが、以下のエラーが発生します。
```
<ランタイムの状態>
キャッチできないエラーが検出されました(2)
×Cannot read property 'document' of undefined
×Cannot read property 'document' of undefined
```
gitをインストールし、適当なディレクトリをソース管理対象として初期化。
その後、「ソース管理」を選択し、現在の状況を表示するだけでも発生します。(手元の環境)
他の拡張は、C/C++, Hex Editor, Japanese Language Pack for VS Code, (+ C# or Python)

その他状況は確認中ですが、今のところ、エラー表示のみとなっています。

**Comment by tshino** [comment]
ありがとうございます！
エラーメッセージのおかげで発生場所の探す範囲が絞れそうです。

念のため確認ですが、エラーが表示されること以外に、
何かの機能が使えないといったような問題は起きていませんか？

すぐには時間が取れないかも知れませんが、修正したいと思います。

**Comment by kato033** [comment]
エラーが出るのみで、特に困った問題は発生してません。
ただ、今日も、ファイル数個のコミットで、45個のエラーメッセージ。気が付いた時は、何が起きたのかと思いました。(実害無かったので、最近まで気づかず)
エラーメッセージの数に意味があるのかと思ったのですが、該当ディレクトリのファイル数でもないようです。初回、ソース管理選択だけで、2個。数ファイルのステージで、44個、コミットしたら、45個。
その間、VSCodeでの編集(エディタ)作業、一切無し、キー入力は、コミットメッセージのみ。何が起きてるのでしょうか。

**Comment by tshino** [comment]
私の所でもようやく、gitの操作で同じエラーメッセージを見ることができました。

**Comment by tshino** [comment]
原因と思われる箇所を見つけて修正しました！

それを先ほどバージョン0.18.1としてリリースしました。
このIssueはこれで閉じます。これで直ると良いですが、もし再発したらお知らせ下さい。
ありがとうございました。

**Comment by kato033** [comment]
対応、ありがとうございます。
