### ISSUE TITLE
要望(機能): 次行先頭へカーソル移動

### ISSUE THREAD

**Issue by kato033** [tshino/vscode-vz-like-keymap#43]
次行先頭へのカーソル位置移動の機能追加はできないでしょうか?

 Vz Editorの頃から、同様の機能を ctrl-J に割り当てて使っていました。

**発端:** Vzの前のUnix環境では、改行キーが ctrl-J ... MS-DOSを使い始めた時、ctrl-J の誤操作が多く、次行先頭に移動を割当て使い始め、現在(WzEditor)では、無いと困る機能となっています。(WzEditorも割当てた)

**VzEditor:** 正確に何を割当てたかは記憶に無いですが、今調べたところ、機能\#4 (Enter)の mi=1,2 (上書きモード)が該当しているかもしれません。([VZマクロ入門](http://mezala.la.coocan.jp/vz/extcmd/cmd04.html))

最終行が改行で終わっていない場合の挙動が不明ですが、サポートしてもらえると助かります。

**Comment by tshino** [comment]
要望をありがとうございます。

ですが、提案されている「次行先頭へのカーソル移動」は
VZやWZで標準的に何かのキーに割り当てられていたものではないとのことなので、
Vz Keymap自体に追加する機能としては不適当かと思います。

Vz Keymapの基本機能はVZエディタが持っていたキーバインドを実現することです。

Vz Keymapは、VZエディタのキーバインドを必要としている私自身や @kato033 さんの
ようなひとのために開発しているものですが、
VZエディタで出来たことをすべて再現することは私には到底不可能ですので、
あくまで標準的なキーバインドの再現が目標なわけです。


さて、VZエディタで強力なマクロ機能が使えたのと同じように、
VS Codeにも強力なカスタマイズ機能がありますので、
ご自身で設定を変更して、お望みの機能を実現することをおすすめします。

少し調べたところ、"macros" という拡張機能が簡単に使えることが分かりました。
https://marketplace.visualstudio.com/items?itemName=geddski.macros

これをインストールして、説明に書かれているように、
実現したい機能を `settings.json` に定義し、
キー割り当てを `keybindings.json` に定義することで使えるようになります。

「次行の先頭へのカーソル移動」の場合、
「行末へのカーソル移動」と「カーソルキー右」を順に実行することで実現できるので、
`settings.json` に次のように書きます。
```
    "macros": {
        "cursorNextLine": [
            "cursorLineEnd",
            "cursorRight"
        ]
    }
```
`cursorNextLine` というのはこの機能に付けた名前です。

そしてこれを `ctrl+j` を割り当てるのであれば、
`keybindings.json` に次の内容を追加します。
```
    {
        "key": "ctrl+j",
        "command": "macros.cursorNextLine"
    }
```
いかがでしょうか？

**Comment by kato033** [comment]
Vz Keymapにもキー未割当のコマンドがあり、元々が Vzにあった機能なので要望としました。
サポートしていただけないという事でしたら、仕方が無いかな、と思います。

VScodeの拡張機能としては、[multi-command](https://marketplace.visualstudio.com/items?itemName=ryuta46.multi-command) というものを見つけ、同様な事ができるかと思いましたが、問題もみつけたところです。(多分、案内頂いた拡張機能と同等と思います)
> 「行末へのカーソル移動」と「カーソルキー右」を順に実行する
これは、画面幅より長い行の場合、途中で画面更新(行末表示 - 次行先頭)が入り、好ましくありません。
「次行移動」-「行先頭」としたところ、「次行移動」が、`vz.cursorDown`だと、表示上、改行されている行で、ダメで、`cursorDown`も行頭が空白の場合、うまくいかない(?) 模様。

元々、VZと同じと言うのは無理があるのでしょうから、この辺はあきらめるか、もう少し考えてみたいと思います。

**Comment by tshino** [comment]
> Vz Keymapにもキー未割当のコマンドがあり、元々が Vzにあった機能なので要望としました。

すみません、これは私の勘違いだったでしょうか？

「次行先頭へのカーソル移動」をVZのマクロ機能を使って独自に
割り当てて使っていた、という風に私は理解していたのですが、
そうではなく、
VZがもともとその機能を持っていて、
設定などですぐにキーに割り当てられる状態だったということでしょうか？

私はVZのマクロ機能を自分で使ったことがないのできちんと理解していませんが、
ご紹介された multi-command のように、
既存の機能を組み合わせて「次行先頭へのカーソル移動」を定義して、
それをキーに割り当てて使っていた、という風に解釈していました。

残念ながら私はもう本物のVZエディタを試せる環境を所有していません。
VZが持っていた機能や仕様についてネットで得られる情報も断片的なため、
「その機能がVZに標準的に備わっていた」かどうかをきちんと判断できません。

なので、もし分かるようでしたら情報を頂けると幸いです。

**Comment by kato033** [comment]
VZがマクロ機能が一つの売りだったかとは思いますが、私の場合、ほぼ、マクロは使っていません。(今も)
まあ、キーへの機能の割当てもマクロと言えば、マクロですが、、。

> 「次行先頭へのカーソル移動」をVZのマクロ機能を使って

VZの機能の一つをキーに割当てただけです。厳密には、オプションがあったようですが。
実際にどうしたかの記憶はあいまいです。

VZの機能については、検索したところ、最初に書いた [VZマクロ入門](http://mezala.la.coocan.jp/vz/extcmd/cmd04.html)) が詳しいと思いました。見出しは「マクロ入門」とありますが、VZが実装している機能が細かく書かれています。(機能は確かに機能番号で定義してあったかと)
次行先頭への移動も(標準で)キーへの割当ての無い機能ですが、機能番号 4(Enter)をオプション付きでキーに割り当てたような気がしています。複数コマンドの組合せで無い事だけは確か。
(そんな面倒な事はしていません。おまけのテトリスマクロでは遊びましたが)

**Comment by tshino** [comment]
丁寧な説明ありがとうございます。
おかげでVZエディタのコマンドの仕組みについての理解がはかどりました。

以下のコマンドを追加します。

- 名前: `vz.cursorNextLineStart`
- 動作:
  - 次の論理行の行頭にカーソルを移動する。
  - カーソルがすでにドキュメントの最終行にある場合は行末に移動。

なお、紹介いただいたVZマクロ入門によると、
上書きモード時の`#04`コマンドは「次の表示行頭へ移動」とあるので、
これから作るコマンドとは少し異なる動作だったのかも知れません。

**Comment by tshino** [comment]
@kato033 さん、
新しいコマンドを追加したバージョンを Vz Keymap v0.18.2 としてリリースしました。

`ctrl+j`に割り当てる場合は、以下のように検索モード用のコマンドも定義すると良いと思います。
検索直後に使ったときに意図せず範囲選択してしまうことを防げます。
```
    {
        "key": "ctrl+j",
        "command": "vz.cursorNextLineStart",
        "when": "editorTextFocus"
    },
    {
        "key": "ctrl+j",
        "command": "vz.findStartCursorNextLineStart",
        "when": "editorTextFocus && findWidgetVisible"
    }
```
もし、また何か気づいたことがあれば遠慮無くお知らせ下さい。
ありがとうございました。

**Comment by kato033** [comment]
対応ありがとうございます。

**Comment by kato033** [comment]
```
 {
        "key": "ctrl+j",
        "command": "vz.findStartCursorNextLineStart",
        "when": "editorTextFocus && findWidgetVisible"
 }
```
ここの部分、"editorTextFocus"でなくて、"editorFocus"ですね。そうしないと、検索ウィンドウからフォーカスが外れません。同様なのが、ctrl-e (vz.cursorUp)/ctrl-x(vz.cursorDown)も。
検索移動後に、その前後のコードを編集しようとして、結構、引っ掛かりました。
まあ、VZ では、検索文字列定義なので、概念が違うから、仕方がないのかも知れません。
ただ、ctrl-s(vz.cursorLeft), ctrl-d(vz.cursorRight)では、ちゃんとカーソル位置が動きます。
仕様ミスマッチ? それとも私の理解不足? なのでしょうか。

**Comment by tshino** [comment]
情報ありがとうございます。
ご指摘の通り、若干ちぐはぐなことになっています。

まず、検索ウィンドウでのカーソル上下キーは検索ワードの履歴から選択する操作になっています。
これはVZエディタでもVS Codeでも共通の動作です。
もちろんVZエディタでは（カーソル上下キーと対応する）Ctrl+EとCtrl+Xも同じ動作をします。
そのため、Vz Keymapでも検索ウィンドウでの上下キー（Ctrl+E, Ctrl+X含む）は履歴を選択する動作に割り当てています。

検索ウィンドウでのカーソル左右キーは**検索ウィンドウ内**のカーソル移動になります。
これもVZエディタとVS Codeで共通の動作です。
もちろんVZエディタでは（カーソル左右キーと対応する）Ctrl+SとCtrl+Dも同じ動作をします。

ところが残念ながら、VS Codeでは検索ウィンドウ内のカーソル移動にカーソル以外のショートカットキーを割り当てることができません。これはVS Codeの現在の仕様です。
そのため、Vz KeymapではVZエディタと同じ動作にすることが出来ないため、次善の策としてドキュメント上でのカーソル移動に割り当てています。

**Comment by tshino** [comment]
追記です。
むしろ Ctrl+E, Ctrl+X が期待と違うということですので、
私からのアドバイスは、検索ウィンドウで検索語を入力したらまずCtrl+M（またはEnter）で確定する、ということです。
これもVZエディタでは当然必要な操作の手順でした。
確定すればドキュメントにフォーカスが移るので、自由にカーソル移動ができます。

VS Codeだと確定しなくても検索が始まって（設定によりますが）カーソルもジャンプしているので、確定する操作が不要に思えるのは確かですけどね。

**Comment by kato033** [comment]
情報、ありがとうございます。 どうも私の理解が違っていたようです。
Ctrl-X, Ctrl-E の問題というより、VSCodeとのマッチングのようです。
VZ Editor的には、検索文字の設定、これが VSCodeでは、検索窓という事ですね。

VZ Editorで、検索文字列を設定した場合、ページ移動(Ctrl-R/Ctrl-C 等)の挙動にのみ影響を与えるのに対し、VSCodeでは、文字列を設定しただけで、カーソル位置が動きます。ここに大きな問題があったという事。

VSCodeで検索文字列を入力しただけで、カーソルが動くので、(VZEditor的には)文字設定済みで移動してると勘違いして、Ctrl-E/Ctrl-Xでそこから、移動しようとする、、が、それが検索履歴への移動になり、ここはどこ? になってました。
また、Ctrl-Lの検索文字設定も同様で、VZEditor的には、検索文字入力にフォーカスが入る事は無いです。(カーソル位置が期待と違う(間違えた)場合、カーソル移動し、再度、Ctrl-Lしたい)

自分の使い方だと、検索文字の履歴は全く使いません。従って、検索ウィンドウ上でのカーソル移動ではなく、エディタ上でのカーソル移動の方が適切となります。
キーマップ変更で対応したいと思います。  ..... 変更が増大中。遅くならならないかちょっと不安。

> 確定する操作が不要に思えるのは確かですけどね。

不要に思えるというより、誤操作の原因。
昔、Emacsのインクリメントサーチが便利かと思ったが、慣れないとトラブルの元。同じ事が起きてます。

**Comment by tshino** [comment]
たしかに、Ctrl+LはVZエディタでは検索ウィンドウを表示しないのに対して、Vz Keymapでは検索ウィンドウにフォーカスを移すので、動作が明確に違いますね。
そもそもVS Codeでは、検索ウィンドウのところに文字列を書き込むAPIが存在しないのでこうなっているわけですが、ちょっと対策できないか考えてみます。
