### ISSUE TITLE
対応括弧へジャンプ機能の挙動

### ISSUE THREAD

**Issue by kato033** [tshino/vscode-vz-like-keymap#48]
ちょっと不自然な挙動があります。

以下のコード
```C#
{
     s = "{[5]}";
}
```
このようなコード(元は C#)で、文字列中の `}` にカーソルがある状態(`]` でも同じ)で、 ctrl-Q K とすると、最後の `}` に移動します。
で、更に ctrl-Q K とすると、最初の `{` に移動。
C の頃だと、文字列中のカッコは単なる文字だったのですが、 C#では、意味を持ったり(正確には `$"{n}"` とか) するので、対応がとれると嬉しいです。
ただ、なんでこんな挙動になるかも不思議。

**Comment by tshino** [comment]
情報ありがとうございます。

Vz Keymapでは対応括弧へのジャンプは `editor.action.jumpToBracket` というVS Codeの既存コマンドを呼び出しているため、その動作はVS Codeの機能ということになります。
この部分のVS Code内部の仕組みには詳しくないのですが、おそらく対応括弧を検索するルールが言語ごとに定義されていて、ファイルの種類に応じて自動的に適切な記号を見つけるのだと思います。

私がよく知っているJavaScriptではバッククオート（\`）で囲んだ文字列の中では
```
const x = "World";
const message = `Hello ${x}`;
```
の2行目のように変数を参照できますが、この2行目にある `}` のところで `ctrl+q ctrl+k` を試したところ、ちゃんとジャンプできました。
C# については詳しくないのですけど、もし言語で対応している文脈で適切なジャンプができないのであれば、バグもしくは要望としてvscodeの公式の方に報告するのが良いと思います。

**Comment by kato033** [comment]
"vz.jumpToBracket" とあったので、Vz Keymapの機能と思っていました。
VSCodeの機能なんですね。 了解しました。
Cのコードっぽい内容だと、同じような挙動となるようです。(新規文書、、*.txtで確認) 一旦、そのような判定がされると、中身を全て削除しても戻らず、、(改めて見ると、カラーリングされていた)
VSCode公式については、少し考えます。仕事だと頑張って英文書きます、という状況なので。

なお、C#の場合、`$"{x}"` で xを参照してくれます。(最近の C#)

**Comment by tshino** [comment]
`vz.jumpToBracket` のようにVz Keymapのコマンドでいったん受けてからVS Codeの既存コマンドを呼び出している理由は、このコマンドをキーボードマクロ記録中に使った場合にそれを記録するためです。
そのため、ほとんどのキーのコマンドをVz Keymapで定義しています。
ちょっと紛らわしいですね。

VS Codeは新規ファイルの場合はファイルの内容から言語を自動判定する仕組みになっていますね。
ウィンドウ右下に判定された言語の名前が表示されて、そこをクリックすると切り替えもできたと思います。
