### ISSUE TITLE
右削除 (vz.deleteAllRight)動作について

### ISSUE THREAD

**Issue by kato033** [tshino/vscode-vz-like-keymap#53]
VZでの動作が分からないので、仕様かも知れませんが、、

ctrl-q y (右削除)[vz.deleteAllRight]は、カーソル位置から、右側を削除する動作となると思いますが、
範囲選択状態で、このコマンドを実行すると、選択部分のみが削除となります。

ctrl-t (単語削除)[vz.deleteWordRight]も同様に選択部分のみ削除されます。

これは仕様でしょうか?

**Comment by tshino** [comment]
質問ありがとうございます。

それらの挙動は、結果として現在の仕様になっています。

というのは、delete系のコマンドは基本的にはVS Codeのdelete系のコマンドを呼び出しているだけだからです。

| Vz Keymapのコマンド | 呼び出しているVS Codeのコマンド |
| ------------------- | ------------------------------- |
| `vz.deleteLeft` | `deleteLeft` |
| `vz.deleteRight` | `deleteRight` |
| `vz.deleteWordLeft` | `deleteWordLeft` |
| `vz.deleteWordRight` | `deleteWordRight` |
| `vz.deleteAllLeft` | `deleteAllLeft` |
| `vz.deleteAllRight` | `deleteAllRight` |

Vz Keymapを無効にしてVS Codeの削除コマンドを試してみれば、同じ挙動であることが確認できると思います。

VS Codeの削除コマンドは基本的には、選択範囲があるときは選択範囲を削除するという挙動です。
ところがご指摘のように、なぜか`deleteAllLeft`だけは動作が異なります。

いずれにしても、これらのコマンドの動作をVz Keymapで一から作り直せば、
一貫性を改善したり、VZエディタの挙動に近づけることが出来ると思いますが、
単語境界の判定などはVS Codeの言語系の拡張などと連携する必要もあると思うので、
作り直すのは得策ではないと考えています。

**Comment by kato033** [comment]
調査、ありがとうございます。
元々は、Vzでの検索で、選択モードに移行するのが面倒だったりするのですが、仕方が無いですね。

------
この問題は、ctrl-Yでの行削除が、検索後にできないことから、の問題。ctrl-Yが選択範囲の削除で、選択範囲が無いとき、行削除となるのが、Vzの仕様から来てます。代わりの方法として、行頭へ移行(なぜか ctrl-E, Ctrl-J)し、右側削除してました。
この問題、確認中に、VSCodeの変な挙動も見ているので、そろそろ、本家へのIssuesも検討かな、、と。
(ショートカット変更で、正しく変更されなかった)
同じ問題が無いか確認する必要があるので、やはり敷居が、、ですね。

**Comment by tshino** [comment]
VS Codeでは検索するとマッチした部分が範囲選択されます。
VZエディタでは範囲選択されなかったと思いますので、そこがいろいろ異なる動作につながります。
検索したあとに`Ctrl+Y`で行削除したい場合はその前に選択解除する必要があるので、`Ctrl+B Ctrl+Y`とすればよいですね。
質問ありがとうございました。

**Comment by kato033** [comment]
既に本題と外れていますが、、、
> Ctrl+B Ctrl+Yとすればよいですね。

これは使えません。慣れの問題もありますが、`Ctrl-B`(手元では無効)はトグル動作かと思います。
検索実行後は、選択中かどうか不明な場合が多いので。
ここで、上移動、次行先頭、、とすると、選択中か分かる事が多く、気が付けば、指が覚えてました。
その後、`Ctrl-K K`で選択解除(正確には、コピーだけど、結果、等価)
長く使ってると色々と変な癖が付くものです。

VSCode、文字列検索すると選択モードに入る事が多く、今、どうしたものかと思案中。
コピーして、該当の場所を検索、貼り付けよう(挿入しよう)とすると、選択中で、置き換えになってしまいます。
慣れの問題もあり、頭痛。複数ファイルでの処理がもう一つ。

**Comment by tshino** [comment]
> > Ctrl+B Ctrl+Yとすればよいですね。
>
> これは使えません。慣れの問題もありますが、Ctrl-B(手元では無効)はトグル動作かと思います。
> 検索実行後は、選択中かどうか不明な場合が多いので。

使えないと思います、ということですが、使えますよ。
検索結果に依らず `Ctrl+B Ctrl+Y` で行けるようになっています。
検索ワード入力直後であれば `Ctrl+B`で選択解除してフォーカスがエディタに戻る動作になっているためです。
分かりにくい仕様ですみません。
