### ISSUE TITLE
CTRL+L直後のカーソル位置の調整

### ISSUE THREAD

**Issue by tshino** [tshino/vscode-vz-like-keymap#64]
CTRL+L（カーソル位置から検索文字列を取得する）の直後にカーソル移動をしたり、ESCキーで検索ウィジェットを閉じたりしたときに、選択状態が解除されてカーソルが現れる位置について、挙動をVZエディタに近づけるように調整する。

もともとVZエディタではCTRL+Lで検索文字列を設定するときに読み取った範囲が選択されることはない。
VS Codeでは基本的に検索することと選択することを独立に制御することが難しいため、Vz KeymapではCTRL+Lによって読み取った文字列の範囲が選択状態になる。
ただし、この状態からのカーソル移動では選択状態を即座に解除することで、あたかも選択状態では無かったかのように振る舞う仕組みにしている。
このとき現在の実装では、常に選択範囲の先頭側にカーソルが現れるようにしている。これはVZエディタの本来の動作に近づけるように決めた仕様。
ただし、事前に検索したい文字列を選択状態にしてからCTRL+Lを使った場合は、VZエディタではカーソル位置が選択範囲の終点側（順方向に選択すれば末尾側、逆に選択すれば先頭側）になるのに対して、選択の方向によってはVz Keymapでは異なる動作になる。
（これは #61 で指摘を頂いた問題）

ここに書いた例は特定の状況の例だが、直そうとすると検索まわりのいろいろな挙動に影響が出ることが予想される。検索まわりの挙動は完全には拡張機能から観測できず制御もしきれないためである。そのため、全体を見ながら良くなる方向を探ってみる。

**Comment by tshino** [comment]
少し対応もれがあったので再調整。
- 文字列を選択 → CTRL+L → CTRL+Q F → ESC
- 文字列を選択 → CTRL+L → CTRL+Q F → CTRL+Q F → ESC
- 文字列を選択 → CTRL+L → CTRL+Q F → CTRL+Q F → カーソル移動
等の場合も最初の文字列選択の時点のカーソル位置を復元するように修正する。
のときの

**Comment by kato033** [comment]
多分、関連と思うので、こちらに

1. Ctrl-L で検索文字列設定
2. Ctrl-C とかで、カーソル移動 (カーソル位置は文字列先頭)
3. ブロック選択(標準で Ctrl-B?) しても有効にならない。

これは、仕様(制限)なのでしょうか?
何をしているかというと、(例えば)ある関数がどこで使われて(定義されて)いるかをまず、ファイル内で探すのですが、無かった時に、grepしようとして、ブロック選択しようとして失敗しています。
(ブロック選択したつもりで、単語末にカーソル移動するが、検索文字とならない)

お手数ですが、確認いただけると助かります。

**Comment by kato033** [comment]
> 3の時点でCTRL+SHIFT+Fを押せばgrepできると思います。

ありがとうございます。そのようですね。

ただ、3の時点ですが、Ctrl-Bのブロック選択/解除でなく、カーソル移動(Ctrl-S/D/E/X, Ctrl-A/F)でもブロック選択解除のようです。本来、ブロック選択中は、これらの操作で解除にならなかったと思うのですが、こちらも制限という事ですね。(これが特殊な状態?)

**Comment by tshino** [comment]
> ただ、3の時点ですが、Ctrl-Bのブロック選択/解除でなく、カーソル移動(Ctrl-S/D/E/X, Ctrl-A/F)でもブロック選択解除のようです。本来、ブロック選択中は、これらの操作で解除にならなかったと思うのですが、こちらも制限という事ですね。(これが特殊な状態?)

これは、VZエディタの動作に近づけた結果、そのような動作になっています。

3の時点のようにCTRL+Cなどで検索結果にジャンプしたときに、VZエディタでは選択モードにはなりません。
（もっというと、CTRL+Bで選択モードにしてから検索した場合は選択モードが継続しますが、VS Codeではその動作の再現は難しいです）

前のコメントに書いたとおり、3の時点はVZエディタの場合と同様に、Vz Keymapでも選択モード（カーソル移動で選択範囲を操作できる状態）ではない扱いです。従って、カーソル移動によって選択範囲を広げたり狭めたりすることはないようになっています。
