### ISSUE TITLE
検索直後に他のタブへ行って戻ったときに選択モードになる

### ISSUE THREAD

**Issue by tshino** [tshino/vscode-vz-like-keymap#67]
CTRL+Lで取得した検索文字列や検索によってマッチした文字列が選択された状態で、いったん他のファイルのタブに切り替えて戻ってくると、選択モード（CTRL+Bで文字列選択するモード）になっている、という問題があるので、直す。

検索文字列やマッチした文字列はVS Codeにとっては選択状態にあるが、Vz Keymapはこの状態を特別扱いしている。
この特別な状態では、カーソル移動（CTRL+Dで右移動など）によって選択範囲の端が移動するような選択モードの動きではなく、何も選択していなかったかのようにカーソルが移動する（結果的に選択状態は解除される）。
こうすることで、検索文字列やマッチした文字列を選択状態にしないVZエディタの動作に近づけている。
ところが、この状態で他の（ファイルを開いている）タブに行って戻ってくると、これが選択モード扱いになってしまっている。
というのがこの問題。

**Comment by kato033** [comment]
失礼します。
この問題ですが、
検索のサイドバー(?)にフォーカスがある場合に、編集画面にフォーカスを移した時、カーソル位置が検索文字にある場合でしょうか?
今も、検索後、編集画面にフォーカスを移すと、検索文字列が選択状態となっています。手元の環境で該当コマンド(シュートカット割付け)が不明(後で確認)ですが、ファイルタブ選択でも同様でした。
これとは別の問題でしょうか?  (最近、やっと気が付いた。不本意に選択モードになってる理由)
VSCodeの問題という事かも知れませんが、確認いただけると嬉しい。

**Comment by tshino** [comment]
ご質問ありがとうございます。

> 検索のサイドバー(?)にフォーカスがある場合に、編集画面にフォーカスを移した時、カーソル位置が検索文字にある場合でしょうか?
> 今も、検索後、編集画面にフォーカスを移すと、検索文字列が選択状態となっています。手元の環境で該当コマンド(シュートカット割付け)が不明(後で確認)ですが、ファイルタブ選択でも同様でした。
> これとは別の問題でしょうか? 

検索文字列が**選択された状態**になることはVS Codeの仕様です。変えられません。

Vz Keymapの**選択モード**と私が呼んでいるのは、SHIFTなどを押さずにカーソルキーを押したときに、選択されている範囲の開始地点が動かずに終了地点だけが動いて選択範囲を広げたり狭めたりできる状態のことです。
通常はCTRL+Bを押すことで選択モードが開始します。
VS Codeが検索文字列を選択された状態にしますが、Vz Keymapとしてはなるべくこれを選択モードではないものとして扱います。ただし、常にそうできるとは限りません。

繰り返しますが、検索操作によって（不本意かも知れませんが）文字列が選択状態になることはVS Codeの仕様です。Vz Keymapでは選択状態の解除はCTRL+BかEscapeでいつでもできるようになっています。

**Comment by kato033** [comment]
確認ありがとうございます。
選択された状態(Vz Keymapの選択モード)になってしまうのは、VSCodeの仕様という事で了解しました。
> Vz Keymapでは選択状態の解除はCTRL+BかEscapeでいつでもできるようになっています。

今選択モードか分かりにくいというのが、問題なので、Ctrl-B(自分のでは違うが)はちょっと微妙。VSCodeは、検索文字列を選択状態に関わらず、色を変えるので、さらに分かりにくく。慣れるか、別の方法を考えたいと思います。
ありがとうございます。
