### ISSUE TITLE
選択中に挿入を行うと、置き換えになる

### ISSUE THREAD

**Issue by kato033** [tshino/vscode-vz-like-keymap#68]
不確かな記憶ですが、
VZの場合、選択中に挿入を行うと、置き換えで無く、単なる挿入だったかと思います。
(VZマクロのサイトの記述もそう)
VSCodeの仕様ではあるかと思いますが、置き換え動作となっています。

VSCodeの仕様からの制限とも言えますが、確認お願いします。

-----
まあ、こちらも本来は、使わない操作なのですが、VSCodeがひたすら、選択状態にしたがるのと、
最近の操作ミス多発の影響から、トラップ状態。
お手数ですが、確認お願いします。

**Comment by tshino** [comment]
ご指摘の通りです。

**Comment by kato033** [comment]
現状、仕様(or 制限)という理解で良いですか?

**Comment by tshino** [comment]
はい。

VS Codeには「上書き」「挿入」というVZエディタのようなモードはなく、例えば

- 文字入力は、選択していないときは挿入、選択しているときは置換（上書き）になる
- 貼り付けは、選択していないときは挿入、選択しているときは置換（上書き）になる

というように選択状態によって2つの機能を実現する基本設計になっていると思います。

また、これらの文字入力や貼り付けは以下のようなVS Codeの機能と深く連携しています。

- 括弧補完（閉じ括弧が自動入力される）、選択中は選択範囲の前後に括弧が挿入される
- 推測候補の表示（IntelliSense）
- 文字入力時に前後の行のインデントの自動調整、行末の空白の自動削除
- 貼り付ける文字列内のインデントの自動調節

もし文字入力や貼り付け時の動作をVZと同じような動作に作り変えてしまうと、これらのVS Codeの高度な連携機能がうまく働かなくなってしまう恐れが高いため、Vz Keymapでは手を付けていない領域になっています。
そのため仕様という理解で間違いありません。

**Comment by kato033** [comment]
了解です。

ただ、
> これらの文字入力や貼り付けは以下のようなVS Codeの機能

ちょっと疑問。大半が大きなお世話って感じてるので。
ふと思ったけど、Viのキーマップサポートってどうなってるのでしょう? 挿入モードが明確に分離されてた。もってもViは、Unixがらみで困った時しか使わないので、基本操作しか覚えてないですが、、。

**Comment by tshino** [comment]
> Viのキーマップサポートってどうなってるのでしょう?

vimであればキーマップ拡張が存在します。
https://marketplace.visualstudio.com/items?itemName=vscodevim.vim
