### ISSUE TITLE
拡張の起動条件の修正

### ISSUE THREAD

**Issue by tshino** [tshino/vscode-vz-like-keymap#81]
vscode拡張の起動条件を指定する `"activationEvents"` の設定を見なおす。

Vz Keymapはキーマップ拡張なのでVS Codeの起動時に一緒にロードさせるために、
```
    "activationEvents": [
        "*"
    ],
```
と設定しているが、`*` を指定するのは非推奨であるとしてパッケージング時にいつも警告されている。
これは、VS Codeの起動を遅くする要因になってしまうからとのこと。

そこで、まだリリースしていないが以下のように変更を行った。
```
    "activationEvents": [
        "onStartupFinished"
    ],
```
これは `*` と微妙に動作が異なり、Vz Keymapのロードタイミングがこれまでよりも遅くなる代わりに、VS Codeの起動完了までユーザーを待たせる時間が短くなる。
この変更はもともと #75 （コードカバレッジの導入）の中で必要があって行った。

これでパッケージング時の警告はなくなったが、ちょっと問題が発生した。
VS Codeの起動直後に素早く、Vz Keymapが提供しているコマンド（カーソルキーなど何でも良い）を呼び出したとき、
```
command 'vz.cursorBottom' not found
```
のような警告が右下にポップアップしてしまう。

これを出ないようにしたい。

**Comment by kato033** [comment]
失礼します。
> のような警告が右下にポップアップしてしまう。

との事ですが、この警告は以前も(昨年秋頃には)、出ていたと思いますが、別モノでしょうか?
この問題は、警告だけでなく、その後のキー操作が不明となっていました(VZ拡張が無効?)

その時は、VSCodeの問題と捉え、VSCodeの処理が追い付いていないのでは? と思ってました。
で、対策は、起動直後はキー操作をしない、、と。

今回の修正で、これが無くなったらば、嬉しいです。

**Comment by tshino** [comment]
>この警告は以前も(昨年秋頃には)、出ていたと思いますが、別モノでしょうか?
> この問題は、警告だけでなく、その後のキー操作が不明となっていました(VZ拡張が無効?)

私は以前のバージョンで遭遇したことは無かったと思うので分かりませんが、
同じメッセージが出ていたのであれば、同様の問題だったかも知れませんね。

私が今回見た症状ではその後のキー操作に問題は発生していません。
起動後に最初に素早く入力したキーが効かないだけで、その後通常通りに使用できます。
もし、Vz Keymapは起動しているのに、Vz Keymapの操作がずっと効かなくなる、という問題がまた起きるようであれば、どんな操作で起きたかなど詳細をお知らせいただけると幸いです。

**Comment by kato033** [comment]
起動直後のキー操作なので、VSCodeの拡張機能読込み前の問題ではないかと、、と思ってます。
別処理(?)で、PCが遅くなった時に発生したと記憶。すぐにキー操作しなければ、回避できるので、その後、遭遇無し。
ただ、発生した時は、ほぼ全ての操作(文字入力以外)が使えず、仕方なく、マウスでVSCodeクローズ。

最近、行削除(Ctrl-Y)の処理が遅く感じてます。似た処理で右削除(Ctrl-Q Ctrl-Y) は速そう。Vz Keymapで違いはあるのでしょうか? VSCodeの問題? とも思っているので、切り分け(いつだ?) できたら、報告しようと思っていますが、とりあえず。(最近、画面更新が追い付かない事が増えつつある)

**Comment by tshino** [comment]
> 最近、行削除(Ctrl-Y)の処理が遅く感じてます。似た処理で右削除(Ctrl-Q Ctrl-Y) は速そう。Vz Keymapで違いはあるのでしょうか? 

Ctrl+Y（`vz.clipboardCutAndPush`など）はVS CodeのCtrl+X（`editor.action.clipboardCutAction`）を使用しない独自処理です。テキストスタック、キーボードマクロ、矩形貼り付けなどVz Keymap独自の機能を実現するための処理を行っている点や、削除後のカーソル位置や選択状態の挙動をVZエディタに寄せていることなどが相違点です。
Ctrl+Q Y（`vz.deleteAllRight`）はVS Codeの`deleteAllRight`コマンドを呼び出して実現しています。Vz Keymapでは削除文字列の復元（Ctrl+U）やキーボードマクロなどのための処理と、削除後のカーソル位置と選択状態をVZエディタに寄せていることなどが相違点です。

**Comment by kato033** [comment]
いつもの作業環境で、起動直後のキー操作を試してみましたが、特に問題はなさそうでした。
何度かは、すぐに反応せず、まとめて動く動作となりましたが、多分OK (押した数、数えてないが)

なお、Ctrl-Yの件は、余分な画面更新が走ってる感じです。(参考まで)

**Comment by tshino** [comment]
検証結果を共有していただきありがとうございます！
